#!/usr/bin/env python3
"""Build index.html (English) and it/index.html (Italian) from src/index.html.

Source markers: [[english||italiano]] keeps one side per page; "@/" is the path to
the site root ("" for the English page, "../" for the Italian one). The pre-commit
hook in .githooks runs this and stages the output, so the site never lags the source.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent
PAIR = re.compile(r"\[\[(.*?)\|\|(.*?)\]\]", re.S)
SRC_NOTE = re.compile(r"<!--src.*?-->\n", re.S)  # notes meant for the source only
NOTE = "<!-- GENERATED by build.py from src/index.html: edit the source, not this file -->\n"
PAGES = {"index.html": (1, ""), "it/index.html": (2, "../")}


def render(src: str, side: int, root: str) -> str:
    out = PAIR.sub(lambda m: m.group(side), SRC_NOTE.sub("", src)).replace("@/", root)
    for leftover in ("[[", "]]", "||"):  # an unbalanced marker would leak into the page
        assert leftover not in out, f"unbalanced marker {leftover!r} in src/index.html"
    return out.replace("<!doctype html>\n", "<!doctype html>\n" + NOTE, 1)


def main() -> None:
    src = (ROOT / "src/index.html").read_text(encoding="utf-8")
    pages = {path: render(src, side, root) for path, (side, root) in PAGES.items()}
    assert pages["index.html"] != pages["it/index.html"], "the two languages came out identical"
    for path, html in pages.items():
        target = ROOT / path
        target.parent.mkdir(exist_ok=True)
        target.write_text(html, encoding="utf-8")
        print("wrote", path)


if __name__ == "__main__":
    main()
